{% set name = "igwn-lldd-lsmp" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: d8f67639eb826e90a571bbe269b7b63b374c26bdd032a41a2f2ec4f39987a3b4

build:
  entry_points:
    - kafka2lsmp = igwn_lldd_lsmp.kafka2lsmp:main
    - lsmp2kafka = igwn_lldd_lsmp.lsmp2kafka:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=38.2.5
  run:
    - configargparse
    - igwn-lldd-common >=0.1.0
    - python >=3.6
    - python-gds

test:
  requires:
    - pip
  commands:
    # check metadata
    - python -m pip check igwn-lldd-lsmp
    - python -m pip show igwn-lldd-lsmp
    # check entry points
    - kafka2lsmp --help
    - lsmp2kafka --help

about:
  home: "https://git.ligo.org/computing/lowlatency/igwn-lldd-lsmp"
  license: "GPL-3.0-or-later"
  license_family: "GPL"
  license_file: "LICENSE"
  summary: The IGWN - Low Latency Data Distribution (lldd) - Ligo Shared Memory Partition (lsmp) is software to distribute low latency data used by the International Gravitational-Wave Observatory Network (IGWN) into the Ligo Shared Memory Partitions.

extra:
  recipe-maintainers:
    - myNameIsPatrick
